apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deploy-tracker-production

resources:
  - ../../base

images:
  - name: ghcr.io/balori/deploy-tracker-api
    newTag: v0.1.0

patches:
  - target:
      kind: Deployment
      name: deploy-tracker-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
