apiVersion: v1
kind: Service
metadata:
  name: deploy-tracker-api
  labels:
    app.kubernetes.io/name: deploy-tracker-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: deploy-tracker-api
  ports:
    - port: 80
      targetPort: http
      name: http
